-I
file
/tmp/vtc-demo/input.ts
--repeat
-P
vtcmonitor
-P
fork
tsp -P zap 4 -O hls --duration 5 --live 5 --playlist /media/ramdisk/live/demo4/index.m3u8 /media/ramdisk/live/demo4/segment.ts
-P
fork
tsp -P zap 5 -O hls --duration 5 --live 5 --playlist /media/ramdisk/live/demo5/index.m3u8 /media/ramdisk/live/demo5/segment.ts
-O
hls
--duration
60
/mnt/Data/catchup/captures/DEMO/catchup.ts
